### ISSUE TITLE
Pubmlst Database XML is empty

### ISSUE THREAD

**Issue by dgslos** [EnzoAndree/FastMLST#4]
Hi,

I'm getting an error with FastMLST: 
`xml.etree.ElementTree.ParseError: no element found: line 1, column 0`

After digging in a bit it appears the xml on pubmlst is empty. Not sure if this is temporary or they will switch completely to the API.
Empty XML: https://pubmlst.org/static/data/dbases.xml
API link to the databases: https://rest.pubmlst.org/db

For now, FastMLST doesn't know what databases are available, so basically doesn't work.

**Comment by EnzoAndree** [comment]
hey @dgslos I think it was temporary, can you confirm that everything works on your side?

**Comment by dgslos** [comment]
Yes! I also emailed pubmlst. Maybe they fixed it after reading my mail. :)
